version: "3"
volumes: 
  mongo_db_data:

services:
  my_mongodb:
    image: mongo:latest
    volumes:
      - mongo_db_data:/data/db

  app:
    build: .
    ports:
      - 3000:3000
    environment:
      # - MONGO_DB_HOSTNAME=172.18.208.1
      - MONGO_DB_HOSTNAME=my_mongodb
      - MONGO_DB_PORT=27017
      - MONGO_DB=lab3
